[workspace]
members = [
    "stry",
    "stry-backend",
    "stry-backend-postgres",
    "stry-backend-sqlite",
    "stry-common",
    "stry-dataloader",
    "stry-frontend",
    "stry-frontend-api",
    "stry-frontend-user",
    "stry-worker",
    "stry-worker-scraper",
]
