[package]
name = "stry"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"
description = "A mini self-hosted Archive of Our Own, a story host with tagging."

license = "MIT"

[dependencies]
fenn = { git = "https://gitlab.com/Txuritan/fenn" }

# Base
anyhow = "1.0"
askama = { version = "0.10", default-features = false }
async-trait = "0.1"
bytes = "0.5"
futures = "0.3"
pin-project = "0.4"
pulldown-cmark  = { version = "0.7", default-features = false }
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "0.2", features = [ "blocking", "rt-threaded", "sync" ] }
tracing = "0.1"
tracing-appender = "0.1"
tracing-log = "0.1"
tracing-flame = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"

# Backend
chrono = { version = "0.4", default-features = false, features = [ "serde" ] }
rand = { version = "0.7" }
rewryte = { git = "https://gitlab.com/Txuritan/rewryte", features = [ "postgres", "sqlite", "serde" ] }
sql-ast = "0.7"

# Backend/PostgreSQL
bb8 = "0.4"
bb8-postgres = "0.4"
postgres-types = { version = "0.1", features = [ "derive" ] }
tokio-postgres = { version = "0.5", features = [ "with-chrono-0_4" ] }

# Backend/SQLite
r2d2 = "0.8"
rusqlite = { version = "0.24", features = [ "bundled", "chrono" ] }

# Frontend
warp = { version = "0.2", default-features = false, features = [ "compression" ] }
warp-macros = { git = "https://gitlab.com/Txuritan/warp-macros" }

# Frontend/API
dataloader = { version = "0.12", default-features = false, features = ["runtime-tokio"] }
juniper = { git = "https://github.com/graphql-rust/juniper", rev = "f19d498254d3e5d2a008c483943facaf3ddcc4fe", default-features = false, features = [ "chrono" ] }
serde_json = "1.0"

# Frontend/User
akibisuto-stylus = { git = "https://gitlab.com/akibisuto/stylus" }
resource = "0.5"
serde_urlencoded = "0.6"

# Scraping
curl = { version = "0.4", features = [ "static-curl", "static-ssl" ] }
html5ever = "0.25"
isahc = { version = "0.9", features = [ "cookies" ] }
lazy_static = "1.4"
markup5ever = "0.10"
markup5ever_arcdom = "0.1"
openssl = { version = "0.10", features = [ "vendored" ] }

# Scraping/EPub
uuid = { version = "0.8", features = [ "v4" ] }

# Other
clap = "2.33"
ctrlc = "3.1"
pest = "2.1"
pest_derive = "2.1"
ron = "0.6"

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "z"
panic = "abort"
