[package]
name = "stry"
version = "2.2.0"
authors = ["Txuritan"]
edition = "2018"

build = "build.rs"

[dependencies]
askama = { git = "https://github.com/djc/askama", rev = "81080812777c7a1998f579908f159e383e3c9a31" }
bcrypt = "0.6"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
futures-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
http = "0.1"
http_req = "0.5"
log = { version = "0.4", features = ["std"] }
postgres = { version = "0.17.0-alpha.1", features = ["with-chrono-0_4"] }
postgres-derive = "0.4.0-alpha.1"
postgres-types = "0.1.0-alpha.1"
r2d2 = "0.8"
r2d2_postgres = "0.16.0-alpha.1"
r2d2_sqlite = "0.12"
rand = "0.7"
rusqlite = { version = "0.20", features = ["bundled", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.6"
story-dl = { version = "0.1", default-features = false }
# signal-hook = { version = "0.1", features = ["tokio-support"] } # wait for windows support
tokio-executor = "=0.2.0-alpha.6"
warp = { git = "https://github.com/seanmonstar/warp", rev = "b4c022871ca995ee2c29276c5000b20b5fd673c1" }

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "z"
panic = "abort"
