[workspace]
members = [
    "stry",
    "stry-backend",
    "stry-backend-postgres",
    "stry-backend-sqlite",
    "stry-client-desktop",
    "stry-common",
    "stry-common-helpers",
    "stry-downloader",
    "stry-frontend",
    "stry-frontend-api",
    "stry-frontend-user",
    "stry-frontend-common",
    "stry-migrate",
    "stry-migrate-common",
]

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "z"
panic = "abort"
