[package]
name = "stry"
version = "2.2.0"
authors = ["Txuritan"]
edition = "2018"

build = "build.rs"

[dependencies]
askama = { git = "https://github.com/djc/askama", rev = "81080812777c7a1998f579908f159e383e3c9a31" }
bcrypt = "0.6"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
futures = "0.1"
http = "0.1"
log = { version = "0.4", features = ["std"] }
postgres = { version = "0.15", features = ["with-chrono"] }
postgres-derive = "0.3"
r2d2 = "0.8"
r2d2_postgres = "0.14"
r2d2_sqlite = "0.12"
rand = "0.7"
rusqlite = { version = "0.20", features = ["bundled", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.6"
story-dl = { version = "0.1", default-features = false }
# signal-hook = { version = "0.1", features = ["tokio-support"] } # wait for windows support
tokio-threadpool = "0.1"
warp = { version = "0.1", default-features = false }

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "z"
panic = "abort"
