[workspace]
members = [
    "stry",
    "stry-backend-postgres",
    "stry-backend-sqlite",
    "stry-common",
    "stry-migrate",
]

[profile.release]
codegen-units = 1
incremental = false
lto = true
opt-level = "z"
panic = "abort"
