[package]
name = "stry2"
version = "2.0.0"
authors = ["Txuritan"]
edition = "2018"

[dependencies]
actix-http = { version="0.2", default-features = false }
actix-rt = "0.2"
actix-web = { version = "1.0", default-features = false }
ammonia = "3"
askama = { version = "0.8" }
chrono = "0.4"
comrak = "0.6"
derive_more = "0.15"
futures = "0.1"
git-version = "0.3"
log = "0.4"
num-format = "0.4"
simple_logger = "1.3"
r2d2 = "0.8.4"
r2d2_sqlite = "0.11"
rusqlite = { version = "0.19", features = ["bundled", "chrono", "uuid"] }
uuid = { version = "0.7", features = ["v4"] }
