version: '2'

tasks:
  build-dev:
    cmds:
      - cargo bom --all > stry-frontend-user/bom.txt
      - cargo build --bin stry
  build-release:
    cmds:
      - cargo bom --all > stry-frontend-user/bom.txt
      - cargo build --bin stry --release

  dot:
    cmds:
      - cargo deps --all-deps --no-transitive-deps --subgraph stry askama crossbeam-channel chrono db-derive log parking_lot serde serde_json serde_urlencoded story-dl rand toml warp > stry.dot

  frame:
    cmds:
      - dframe http://localhost:8901 --delay 5 --frame "Apple Thunderbolt Display, Microsoft Surface Pro 4, Samsung Galaxy S7" --output assets/pictures

  generate-dal:
    cmds:
      - cargo build --bin stry-migrate
#      - cargo run --bin stry-migrate -- dal generate --style postgres stry-common/schema.dal stry-backend-postgres/schema.sql
      - cargo run --bin stry-migrate -- dal generate --style sqlite stry-common/schema.dal stry-backend-sqlite/schema.sql

  test:
    cmds:
      - cargo test --package stry-backend-sqlite
