version: '2'

tasks:
  dot:
    cmds:
      - cargo deps --all-deps --no-transitive-deps --subgraph stry askama crossbeam-channel chrono db-derive log parking_lot serde serde_json serde_urlencoded story-dl rand toml warp > stry.dot

  frame:
    cmds:
      - dframe http://localhost:8901 --delay 5 --frame "Apple Thunderbolt Display, Microsoft Surface Pro 4, Samsung Galaxy S7" --output assets/pictures

  generate-ddl:
    cmds:
      - cargo build --bin stry-migrate
      - cargo run --bin stry-migrate -- ddl generate --style postgres schema.ron stry-backend-postgres/schema.sql
      - cargo run --bin stry-migrate -- ddl generate --style sqlite schema.ron stry-backend-sqlite/schema.sql
