version: '2'

tasks:
  css:
    cmds:
      - rsass --style Compressed ./scss/index.scss > ./css/polygon.css
    sources:
      - scss/**/*.scss
    generates:
      - css/polygon.css

  build:
    deps: [css]
    cmds:
      - cargo build --release
