[package]
name = "stry-evermore"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

license = "MIT"

workspace = ".."

[dependencies]
# Core
stry-config = { path = "../stry-config" }

# Crate
anyhow = "1.0"
futures = "0.3"
tracing = "0.1"
tracing-futures = "0.2"
