CREATE TABLE IF NOT EXISTS Settings (
  Key TEXT NOT NULL,
  Value TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Key)
);

CREATE TABLE IF NOT EXISTS Author (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Chapter (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Pre TEXT NOT NULL,
  Main TEXT NOT NULL,
  Post TEXT NOT NULL,
  Words INTEGER NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Story (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Summary TEXT NOT NULL,
  Rating TEXT NOT NULL,
  State TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Character (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Origin (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Pairing (
  Id TEXT NOT NULL,
  Hash TEXT NOT NULL,
  Platonic BOOLEAN NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Tag (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Warning (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS StoryAuthor (
  StoryId TEXT NOT NULL,
  AuthorId TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (StoryId, AuthorId),
  FOREIGN KEY (StoryId) REFERENCES Story(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (AuthorId) REFERENCES Author(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS StoryChapter (
  StoryId TEXT NOT NULL,
  ChapterId TEXT NOT NULL,
  Place INTEGER NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (StoryId, ChapterId),
  FOREIGN KEY (StoryId) REFERENCES Story(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (ChapterId) REFERENCES Chapter(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS StoryCharacter (
  StoryId TEXT NOT NULL,
  CharacterId TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (StoryId, CharacterId),
  FOREIGN KEY (StoryId) REFERENCES Story(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (CharacterId) REFERENCES Character(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS StoryOrigin (
  StoryId TEXT NOT NULL,
  OriginId TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (StoryId, OriginId),
  FOREIGN KEY (StoryId) REFERENCES Story(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (OriginId) REFERENCES Origin(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS StoryPairing (
  StoryId TEXT NOT NULL,
  PairingId TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (StoryId, PairingId),
  FOREIGN KEY (StoryId) REFERENCES Story(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (PairingId) REFERENCES Pairing(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS StoryTag (
  StoryId TEXT NOT NULL,
  TagId TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (StoryId, TagId),
  FOREIGN KEY (StoryId) REFERENCES Story(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (TagId) REFERENCES Tag(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS StoryWarning (
  StoryId TEXT NOT NULL,
  WarningId TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (StoryId, WarningId),
  FOREIGN KEY (StoryId) REFERENCES Story(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (WarningId) REFERENCES Warning(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS PairingCharacter (
  PairingId TEXT NOT NULL,
  CharacterId TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (PairingId, CharacterId),
  FOREIGN KEY (PairingId) REFERENCES Pairing(Id) ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY (CharacterId) REFERENCES Character(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS Worker (
  Site TEXT NOT NULL,
  Task TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Site),
  FOREIGN KEY (Task) REFERENCES WorkerTask(Id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS WorkerTask (
  Id TEXT NOT NULL,
  Site TEXT NOT NULL,
  Url TEXT NOT NULL,
  Chapter INTEGER NOT NULL,
  Completed BOOLEAN NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerAuthor (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerChapter (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Pre TEXT NOT NULL,
  Main TEXT NOT NULL,
  Post TEXT NOT NULL,
  Words INTEGER NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerStory (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Summary TEXT NOT NULL,
  Rating TEXT NOT NULL,
  State TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerCharacter (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerOrigin (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerPairing (
  Id TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerTag (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS WorkerWarning (
  Id TEXT NOT NULL,
  Name TEXT NOT NULL,
  Created DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  Updated DATETIME NOT NULL DEFAULT (DATETIME('now', 'utc')),
  PRIMARY KEY (Id)
);
