[package]
name = "stry-scraper"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

license = "MIT"

workspace = ".."

[dependencies]
# Crate
anyhow = "1.0"
html5ever = "0.25"
markup5ever = "0.10"
markup5ever_arcdom = "0.1"
