[package]
name = "stry-quarry"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

license = "MIT"

workspace = ".."

[features]
stry-types = [ "stry-models" ]

[dependencies]
# Core
stry-models = { path = "../stry-models", optional = true }

# Crate
fnv = "1.0"
