[package]
name = "stry"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

workspace = ".."

[features]
default = ["postgresql", "sqlite"]

postgresql = ["postgres", "postgres-derive", "postgres-types"]
sqlite = ["rusqlite", "libsqlite3-sys"]

[dependencies]
stry-common = { path = "../stry-common" }

## Core
anyhow = "1.0"
crossbeam-channel = "0.4"
parking_lot = "0.10"
pin-project = "0.4"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
tracing-log = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"

## Site
akibisuto-stylus = "0.1"
deadqueue = "0.1"
either = { version = "1.5", features = ["serde"] }
enum-map = "0.6"
pest = "2.1"
serde_json = "1.0"
story-dl = { version = "0.3", default-features = false }
toml = "0.5"

## Web Server
askama = { version = "0.9", default-features = false }
futures = "0.3"
futures-util = "0.3"
resource = "0.4"
serde_urlencoded = "0.6"
tokio = { version = "0.2", features = ["blocking", "macros", "rt-core", "signal", "sync"] }
tokio-executor = "0.2.0-alpha.6"
warp = { version = "0.2", default-features = false, features = ["websocket"] }

## Database
chrono = { version = "0.4", default-features = false, features = ["serde"] }
db-derive = "0.1"
r2d2 = "0.8"
rand = "0.7"

postgres = { version = "0.17", features = ["with-chrono-0_4"], optional = true }
postgres-derive = { version = "0.4", optional = true }
postgres-types = { version = "0.1", optional = true }

rusqlite = { version = "=0.21.0", features = ["bundled", "chrono"], optional = true }
libsqlite3-sys = { version = "=0.17.3", optional = true }
