[package]
name = "stry-backend-sqlite"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

build = "build.rs"

workspace = ".."

[dependencies]
stry-common = { path = "../stry-common", features = [ "types-sqlite" ] }

# Core
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "0.2", features = [ "blocking" ] }
tracing = "0.1"

# Database
chrono = { version = "0.4", default-features = false, features = [ "serde" ] }
r2d2 = "0.8"
r2d2_sqlite = "0.15"
rusqlite = { version = "0.22", features = [ "bundled", "chrono" ] }
