[package]
name = "stry-backend"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

license = "MIT OR Apache-2.0"

workspace = ".."

[dependencies]
fenn = { git = "https://gitlab.com/Txuritan/fenn.git", default-features = false }

stry-common = { path = "../stry-common" }

# Core
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }

# Database
stry-backend-postgres = { path = "../stry-backend-postgres" }
stry-backend-sqlite = { path = "../stry-backend-sqlite" }
