[package]
name = "stry-backend-postgres"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

build = "build.rs"

workspace = ".."

[dependencies]
stry-common = { path = "../stry-common" }

# Core
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = [ "derive" ] }
tracing = "0.1"

# Database
chrono = { version = "0.4", default-features = false, features = [ "serde" ] }
