[package]
name = "stry-common-helpers"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

license = "MIT OR Apache-2.0"

workspace = ".."

[dependencies]
stry-common = { path = "../stry-common" }

chrono = { version = "0.4", default-features = false }
