[package]
name = "stry-common"
version = "2.3.0"
authors = [ "Txuritan <txuritan@protonmail.com>" ]
edition = "2018"

build = "build.rs"

workspace = ".."

[features]
sqlite-types = [ "rusqlite" ]

[dependencies]
# Core
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }

# Database
chrono = { version = "0.4", default-features = false, features = ["serde"] }
rusqlite = { version = "0.22", features = [ "bundled" ], optional = true }

# Search
pest = "2.1"
pest_derive = "2.1"
